deep_sort:
  max_age: 30
  n_init: 3
  nms_max_overlap: 1.0
  max_cosine_distance: 0.3
  nn_budget: null

visualization:
  colors:
    motorcycle: [0, 255, 0]
    car: [0, 0, 255]
    truck: [255, 0, 0]